# Generated by Django 5.2.6 on 2025-09-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название двигателя')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название судна')),
                ('imo_number', models.CharField(max_length=20, unique=True, verbose_name='IMO номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Судно',
                'verbose_name_plural': 'Судна',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время замера')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура, °C')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Давление, бар')),
                ('rpm', models.FloatField(blank=True, null=True, verbose_name='Обороты, об/мин')),
                ('fuel_consumption', models.FloatField(blank=True, null=True, verbose_name='Расход топлива, л/ч')),
                ('oil_pressure', models.FloatField(blank=True, null=True, verbose_name='Давление масла, бар')),
                ('coolant_temperature', models.FloatField(blank=True, null=True, verbose_name='Температура охлаждающей жидкости, °C')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.engine', verbose_name='Двигатель')),
            ],
            options={
                'verbose_name': 'Замер',
                'verbose_name_plural': 'Замеры',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='engine',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.vessel', verbose_name='Судно'),
        ),
    ]
