# Generated by Django 5.2.6 on 2025-09-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_engine_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitoring.engine', verbose_name='Двигатель'),
        ),
    ]
