# Generated by Django 5.2.6 on 2025-09-22 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_measurement_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название параметра')),
                ('code', models.SlugField(unique=True, verbose_name='Код параметра')),
                ('unit', models.CharField(choices=[('°C', 'Градусы Цельсия'), ('бар', 'Бар'), ('об/мин', 'Обороты в минуту'), ('л/ч', 'Литр в час'), ('кПа', 'Килопаскаль'), ('%', 'Проценты'), ('л', 'Литр'), ('кг', 'Килограмм'), ('В', 'Вольт'), ('А', 'Ампер'), ('кВт', 'Киловатт'), ('кВт·ч', 'Киловатт-час'), ('дБ', 'Децибел'), ('мм', 'Миллиметр'), ('м/с', 'Метр в секунду'), ('', 'Без единиц')], max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип параметра',
                'verbose_name_plural': 'Типы параметров',
            },
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='coolant_temperature',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='fuel_consumption',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='oil_pressure',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='rpm',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='temperature',
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='monitoring.measurement', verbose_name='Замер')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.parametertype', verbose_name='Тип параметра')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'unique_together': {('measurement', 'parameter_type')},
            },
        ),
    ]
